config/routes.rb
Vvv::Application.routes.draw do

  get "challenges/accept"
  get "challenges/edit"
  get "challenges/new"
  resources :challenges

  root :to => "challenges#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end

  def accept
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_add_to_challenge.html.haml
.add_to_challenge
  %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
  = button_to "Add To Challenge!", "#", {:class => "add"}

app/views/challenges/_comments.html.haml
.comments 
  %h2 Comments
  %table
    %tr
      %td
        - form_for "#" do |f|
          = f.label :name, "Name"
          = f.text_field :name
          = f.label :email, "Email"
          = f.text_field :email
          = f.label :website, "Website"
          = f.text_field :website
          = f.label :comment, "Comment"
          = f.text_area :comment, :rows => "5"
          %br/
          = f.submit "Comment", :disable_with => 'Submitting Comment...'
    %tr
      %td
        %p.commenter Commie Commenter 11/11/11 at 11:11:11 a.m.
        %p Pork chop turducken spare ribs meatball shankle. Kielbasa ribeye tongue, pork belly swine meatball chicken brisket capicola venison. Kielbasa cow shankle spare ribs, fatback capicola sirloin ground round. Pork belly andouille ribeye, meatball tail cow corned beef beef pancetta jerky short loin. Brisket bacon pork, bresaola ham tri-tip meatball ground round pastrami. Rump spare ribs venison chuck sausage flank. Tongue rump hamburger pork loin, biltong ground round shankle pastrami.
    %tr
      %td
        %p.commenter Commie Commenter 11/11/11 at 11:11:11 a.m.
        %p Pork belly andouille ribeye, meatball tail cow corned beef beef pancetta jerky short loin. Brisket bacon pork, bresaola ham tri-tip meatball ground round pastrami. Rump spare ribs venison chuck sausage flank. Tongue rump hamburger pork loin, biltong ground round shankle pastrami.
    %tr
      %td
        %p.commenter Commie Commenter 11/11/11 at 11:11:11 a.m.
        %p Brisket bacon pork, bresaola ham tri-tip meatball ground round pastrami. Rump spare ribs venison chuck sausage flank. Tongue rump hamburger pork loin, biltong ground round shankle pastrami.
    %tr
      %td
        %p.commenter Commie Commenter 11/11/11 at 11:11:11 a.m.
        %p Tongue rump hamburger pork loin, biltong ground round shankle pastrami.

app/views/challenges/_youtube_search.haml
.youtube_search 
  - form_for "#" do |f|
    = f.text_field :name, :value => "Search YouTube", :class => "search_box"
    = f.submit "Go!", :disable_with => 'Searching...', :class => "go_button"

app/views/challenges/accept.html.haml
<h1>Challenges#accept</h1>
<p>Find me in app/views/challenges/accept.html.erb</p>

app/views/challenges/edit.html.haml
%h2 Open Challenge
.open_challenge
  .challenger
    %embed#challenger_1{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "250"}
  .challenger
    .open

.clearfix
= render 'youtube_search'
.search_results
  - (1..9).each do |i|
    = render 'add_to_challenge'

app/views/challenges/index.html.haml
<h1>Challenges#index</h1>
<p>Find me in app/views/challenges/index.html.erb</p>

app/views/challenges/new.html.haml
%h2 Start A Challenge
= render 'youtube_search'
.search_results
  - (1..9).each do |i|
    = render 'add_to_challenge'

app/views/challenges/show.html.haml
%h2 Featured Bout
.challenge
  .challenger
    %embed#challenger_1{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "250"}
    %div{:class => "challenger_1 votes"} 
      %table{:width => "100%"}
        %tr
          %th Challenger 1
        %tr
          %td{:class => "vote_count"} 567
        %tr
          %td
            = button_to "Vote!", "#", {:class => "vote"}
  .challenger
    %embed#challenger_2{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "250"}
    %div{:class => "challenger_2 votes"}
      %table{:width => "100%"}
        %tr
          %th Challenger 2
        %tr
          %td{:class => "vote_count"} 567
        %tr
          %td 
            = button_to "Vote!", "#", {:class => "vote"}
  .clearfix

.clearfix
= render 'comments' 

app/views/layouts/_about.html.haml
%h2 About Us
%p Spare ribs bresaola ball tip capicola tenderloin, pancetta ham hock t-bone. Pork kielbasa leberkäse tri-tip short ribs boudin. Biltong tail pork, leberkäse short ribs shankle ham andouille tri-tip fatback rump jerky prosciutto. Pig chicken spare ribs strip steak meatloaf short ribs, ball tip pork chop frankfurter beef ribs drumstick pancetta. Tail cow meatloaf ball tip, chuck prosciutto pig jerky pastrami shankle. Rump sirloin bresaola, fatback chicken tail shank drumstick. Shankle salami boudin turducken, kielbasa rump chuck t-bone.
%p Tongue venison flank kielbasa, chicken pork chop jerky pancetta meatball tenderloin brisket turkey. Venison tail boudin ham, pork chop spare ribs strip steak shank ball tip corned beef. Ground round ham leberkäse shoulder, tail boudin tongue pancetta t-bone filet mignon short loin spare ribs. Shankle shoulder swine, meatball jerky ham hock pig short loin pork belly bacon kielbasa. Sirloin corned beef chicken, biltong pastrami tail drumstick hamburger tri-tip. Short ribs short loin pork belly swine prosciutto, ball tip jowl. Meatball frankfurter swine shoulder, tenderloin bresaola hamburger chuck tail venison jerky short loin.

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}, VideoVersusVideo.com

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title
  == #{ controller.controller_name.titleize } - #{ controller.action_name.titleize }
  
%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag 'modernizr.min', 'respond.min'

= csrf_meta_tag

app/views/layouts/_header.html.haml
#logo
  %h1 Video Versus Video
#start_challenge
  =link_to "Start A Challenge", challenges_path
.clearfix

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
/ - if !google_api_key.blank?
/   = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
/   :javascript
/     google.load(#{ remote_jquery("1.6") });
/ - else
/   = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.6") }"

-# fall back to local jQuery if necessary
:javascript
  window.jQuery || document.write("<script src='/javascripts/jquery.min.js'>\x3C/script>")

= javascript_include_tag 'jquery-ui.min'
  
= javascript_include_tag 'rails', 'plugins', 'application' 
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"],["_trackPageLoadTime"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

app/views/layouts/_sidebar.html.haml
%h3{:class => "blue"}
  =link_to "Challenges", "#"
%div
  - (1..2).each do |i|
    %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
    %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
    .clearfix

%h3{:class => "green"}
  =link_to "Open Challenges", "#"  
%div
  - (1..2).each do |i|
    %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
    %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
    .clearfix

%h3{:class => "red"}
  =link_to "Hall of Fame", "#"
%div
  - (1..2).each do |i|
    %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
    %embed{:src => "http://www.youtube.com/v/JpBGRA6HHtY", :width => "175"}
    .clearfix

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    -# To render a different stylesheet partial inside the head (i.e. for admin layout)
    -# just copy _stylesheets.html.haml, and point to that partial instead.
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
  
  %body{ :class => "#{controller.controller_name}" }
    #container
      %header#header
        = render "layouts/header"
        
      #main{ :role => 'main' }
        = render "layouts/flashes"
        = yield
      
      #sidebar
        = render "layouts/sidebar"
        
      .clearfix
        
      #about
        = render "layouts/about"
        
      %footer#footer
        = render "layouts/footer"
        
    -# Javascript at the bottom for fast page loading
    = render "layouts/javascripts"